
db.Departments.drop()
db.Departments.insert({ "Name":"Barcelona", "_id":"D01"})
db.Departments.insert({ "Name":"Girona", "_id":"D02"})
db.Departments.insert({ "Name":"Lleida", "_id":"D03"})
db.Departments.insert({ "Name":"Tarragona", "_id":"D04"})


db.Towns.drop()
db.Towns.insert({ "Department" : "D01", "Name": "Alella", "_id":"D01.T01"})
db.Towns.insert({ "Department" : "D01", "Name": "Abrera", "_id":"D01.T02"})
db.Towns.insert({ "Department" : "D01", "Name": "Badalona", "_id":"D01.T03"})
db.Towns.insert({ "Department" : "D01", "Name": "Badia del Vallès", "_id":"D01.T04"})
db.Towns.insert({ "Department" : "D01", "Name": "Barberà del Vallès", "_id":"D01.T05"})
db.Towns.insert({ "Department" : "D01", "Name": "Barcelona", "_id":"D01.T06"})
db.Towns.insert({ "Department" : "D01", "Name": "Begues", "_id":"D01.T07"})
db.Towns.insert({ "Department" : "D01", "Name": "Cabrera de Mar", "_id":"D01.T08"})
db.Towns.insert({ "Department" : "D01", "Name": "Castellbisbal", "_id":"D01.T09"})
db.Towns.insert({ "Department" : "D01", "Name": "Castelldefels", "_id":"D01.T10"})
db.Towns.insert({ "Department" : "D01", "Name": "Cerdanyola del Vallès", "_id":"D01.T11"})
db.Towns.insert({ "Department" : "D01", "Name": "Cervelló", "_id":"D01.T12"})
db.Towns.insert({ "Department" : "D01", "Name": "Corbera de Llobregat", "_id":"D01.T13"})
db.Towns.insert({ "Department" : "D01", "Name": "Cornellà de Llobregat", "_id":"D01.T14"})
db.Towns.insert({ "Department" : "D01", "Name": "El Masnou", "_id":"D01.T15"})
db.Towns.insert({ "Department" : "D01", "Name": "El Papiol", "_id":"D01.T16"})
db.Towns.insert({ "Department" : "D01", "Name": "El Prat de Llobregat", "_id":"D01.T17"})
db.Towns.insert({ "Department" : "D01", "Name": "Esparraguera", "_id":"D01.T18"})
db.Towns.insert({ "Department" : "D01", "Name": "Esplugues de Llobregat", "_id":"D01.T19"})
db.Towns.insert({ "Department" : "D01", "Name": "Gavà", "_id":"D01.T20"})
db.Towns.insert({ "Department" : "D01", "Name": "Granollers", "_id":"D01.T21"})
db.Towns.insert({ "Department" : "D01", "Name": "L'Hospitalet de Llobregat", "_id":"D01.T22"})
db.Towns.insert({ "Department" : "D01", "Name": "La Palma de Cervelló", "_id":"D01.T23"})
db.Towns.insert({ "Department" : "D01", "Name": "La Roca del Vallès", "_id":"D01.T24"})
db.Towns.insert({ "Department" : "D01", "Name": "Matadepera", "_id":"D01.T25"})
db.Towns.insert({ "Department" : "D01", "Name": "Mataró", "_id":"D01.T26"})
db.Towns.insert({ "Department" : "D01", "Name": "Molins de Rei", "_id":"D01.T27"})
db.Towns.insert({ "Department" : "D01", "Name": "Mollet del Vallès", "_id":"D01.T28"})
db.Towns.insert({ "Department" : "D01", "Name": "Montcada i Reixac", "_id":"D01.T29"})
db.Towns.insert({ "Department" : "D01", "Name": "Montgat", "_id":"D01.T30"})
db.Towns.insert({ "Department" : "D01", "Name": "Montornès del Vallès", "_id":"D01.T31"})
db.Towns.insert({ "Department" : "D01", "Name": "Pallejà", "_id":"D01.T32"})
db.Towns.insert({ "Department" : "D01", "Name": "Parets del Vallès", "_id":"D01.T33"})
db.Towns.insert({ "Department" : "D01", "Name": "Premià de Mar", "_id":"D01.T34"})
db.Towns.insert({ "Department" : "D01", "Name": "Ripollet", "_id":"D01.T35"})
db.Towns.insert({ "Department" : "D01", "Name": "Sabadell", "_id":"D01.T36"})
db.Towns.insert({ "Department" : "D01", "Name": "Sant Adrià de Besòs", "_id":"D01.T37"})
db.Towns.insert({ "Department" : "D01", "Name": "Sant Andreu de la Barca", "_id":"D01.T38"})
db.Towns.insert({ "Department" : "D01", "Name": "Sant Boi de Llobregat", "_id":"D01.T39"})
db.Towns.insert({ "Department" : "D01", "Name": "Sant Climent de Llobregat", "_id":"D01.T40"})
db.Towns.insert({ "Department" : "D01", "Name": "Sant Cugat del Vallès", "_id":"D01.T41"})
db.Towns.insert({ "Department" : "D01", "Name": "Sant Feliu de Llobregat", "_id":"D01.T42"})
db.Towns.insert({ "Department" : "D01", "Name": "Sant Joan Despí", "_id":"D01.T43"})
db.Towns.insert({ "Department" : "D01", "Name": "Sant Just Desvern", "_id":"D01.T44"})
db.Towns.insert({ "Department" : "D01", "Name": "Sant Pere de Ribes", "_id":"D01.T45"})
db.Towns.insert({ "Department" : "D01", "Name": "Sant Vicenç dels Horts", "_id":"D01.T46"})
db.Towns.insert({ "Department" : "D01", "Name": "Santa Coloma de Cervelló", "_id":"D01.T47"})
db.Towns.insert({ "Department" : "D01", "Name": "Santa Coloma de Gramenet", "_id":"D01.T48"})
db.Towns.insert({ "Department" : "D01", "Name": "Sitges", "_id":"D01.T49"})
db.Towns.insert({ "Department" : "D01", "Name": "Terrassa", "_id":"D01.T50"})
db.Towns.insert({ "Department" : "D01", "Name": "Tiana", "_id":"D01.T51"})
db.Towns.insert({ "Department" : "D01", "Name": "Torrelles de Llobregat", "_id":"D01.T52"})
db.Towns.insert({ "Department" : "D01", "Name": "Vacarisses", "_id":"D01.T53"})
db.Towns.insert({ "Department" : "D01", "Name": "Vallirana", "_id":"D01.T54"})
db.Towns.insert({ "Department" : "D01", "Name": "Viladecavalls", "_id":"D01.T55"})
db.Towns.insert({ "Department" : "D01", "Name": "Viladecans", "_id":"D01.T56"})
db.Towns.insert({ "Department" : "D01", "Name": "Vilanova i la Geltrú", "_id":"D01.T57"})
db.Towns.insert({ "Department" : "D01", "Name": "Vilassar de Mar", "_id":"D01.T58"})

db.Towns.insert({ "Department" : "D02", "Name": "Girona", "_id":"D02.T01"})

db.Towns.insert({ "Department" : "D03", "Name": "La Seu d'Urgell", "_id":"D03.T01"})
db.Towns.insert({ "Department" : "D03", "Name": "Lleida", "_id":"D03.T02"})
db.Towns.insert({ "Department" : "D03", "Name": "Oliana", "_id":"D03.T03"})
db.Towns.insert({ "Department" : "D03", "Name": "Peramola", "_id":"D03.T04"})
db.Towns.insert({ "Department" : "D03", "Name": "Solsona", "_id":"D03.T05"})
db.Towns.insert({ "Department" : "D03", "Name": "Tragó de Peramola", "_id":"D03.T06"})


db.Towns.insert({ "Department" : "D04", "Name": "Tarragona", "_id":"D04.T01"})